apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-seed-application
  namespace: argocd
spec:
  project: default

  source: 
    repoURL: git@github.com:simcax/cluster-config.git
    targetRevision: HEAD
    path: c02/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - "CreateNamespace=true"
    automated:
      selfHeal: true
      prune: true